name: Update Ruwanweli Saya Deshana series Lesson Links

on:
  push:
    paths:
      - 'VisheshaDeshana/RuwanweliMahaSeya/RuwanweliMahaSeya_ytlinks.txt'     
      - 'VisheshaDeshana/RuwanweliMahaSeya/RuwanweliMahaSeya_notes.txt'       
   
jobs:
  run-python-script-RuwanweliMahaSeya:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 # Set your desired Python version

      - name: Read RuwanweliMahaSeya_series
        run: python scripts/gen_series_RuwanweliMahaSeya.py

      - name: commit changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -a -m "updated RuwamweliMahaSeya series"
          git push
