name: Update menus when navigation_header_template.html is updated

on:
  push:
    paths:
      - 'scripts/templates/navigation_header_template.html'

  pull_request:
    branches:
      - main
    paths:
      - 'scripts/templates/navigation_header_template.html'
 
jobs:
  run-SuthraPathrika-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11 # Set your desired Python version

      - name: update menus for past series
        run: python scripts/gen_series_past.py
      
      - name: update menus Aniththa Dukka Anaththa and Paramartha Video series
        run: python scripts/gen_navbar_replace.py

      - name: commit changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git commit -a -m "Updated Suthra Pathrika List"
          git push
